### ISSUE TITLE
Need to use the latest version of nfsprovisioner for security 

### ISSUE THREAD

**Issue by Jooho** [Jooho/nfs-provisioner-operator#10]
This is the new repo for nfsprovisioner : https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner
The latest image is here: k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.0

**Comment by davidkarlsen** [comment]
related: https://github.com/Jooho/nfs-provisioner-operator/issues/13

**Comment by davidkarlsen** [comment]
@Jooho maybe the default in https://github.com/Jooho/nfs-provisioner-operator/blob/main/api/v1alpha1/nfsprovisioner_types.go#L70 should be updated to use `k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.0` then?
